version: '3'
services:
  portfolio:
    build: ./
    container_name: portfolio
    command: pnpm run dev --host
    environment:
      PORT: 3000
      NODE_ENV: "development"
    ports:
      - 3000:3000
    volumes:
      - ./:/portfolio